services:
  web:
    build: .
    ports:
      - '5173:4173'
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    depends_on:
      - backend
  backend:
    image: postgres:16-alpine
    ports:
      - '8080:8080'
